name: Deploy Swagger in GitHub Pages

on:
  push:
    branches:
      - '**'

jobs:
  GenerateSwagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Security
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: 'maven'
      - run: chmod +x mvnw
      - name: Execute project
        run: |
              ./mvnw spring-boot:run
              ./mvnw springdoc-openapi:generate

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi/docs/asciidoc/swagger.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
