name: Run tests API

on:
  push:
    branches:
    - master

env:
  MAVEN_OPTS: -Dmaven.repo.local=maven_repository
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}

    - name: Build and test
      run: |
        ./mvnw clean install
        
    - name: Generate JUnit report
      run: |
        mkdir -p target/surefire-reports
        find target/test-classes -name "TEST-*.xml" -exec cp {} target/surefire-reports/ \;

    - name: Upload JUnit report
      uses: actions/upload-artifact@v2
      with:
        name: junit-report
        path: target/surefire-reports
