name: Run tests API

on:
  push:
    branches:
    - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## Etapa 1 - Criacao da copia do repositorio
    - name: Checkout Security
      uses: actions/checkout@v3
      
    ## Etapa 2 - Configuração JDK
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
        
    ## Etapa 3 - Construcao dos testes
    - name: Build test
      run: mvn --batch-mode -DskipTests package
