name: Run tests API

on:
  push:
    branches:
    - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## Etapa 1 - Criacao da copia do repositorio
    - name: Checkout Security
      uses: actions/checkout@v3
      
    ## Etapa 2 - Configuração JDK
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
        
    ## Etapa 3 - Construcao dos testes
    - name: Build test
      run: mvn --batch-mode -DskipTests package
      
    ## Etapa 4 -  Execucao dos Testes
    - name: Run test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      
   # aqui criamos a pasta para armazenar o relatório dos testes
    - run: mkdir coverage-report && cp -r target/site/jacoco/* coverage-report

      # aqui utilizamos um action para registrar o resultado do teste no nosso workflow,
      # caso ocorra alguma falha em algum teste, ficará explicito nos logs de execução aba Actions
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

      # aqui utilizamos um action para fazer a publicação do relatório de testes,
      # esse relatório pode ser baixado nos detalhes de execução do workflow
    - uses: actions/upload-artifact@v2
      with:
        name: Test Coverage Report
        path: coverage-report
